[project]
authors = ["Kanishk Jain, Michael Hess (Pixi packaging)"]
channels = ["conda-forge"]
description = "Pixi environment to run motionmapperpy"
name = "motionmapperpy"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = "<2.0"
moviepy = "1.0.3"
h5py = ">=3.14.0,<4"
hdf5storage = ">=0.1.19,<0.2"
scipy = ">=1.15.2,<2"
matplotlib = ">=3.10.3,<4"
cupy = ">=13.4.1,<14"


[pypi-dependencies]
scikit-image = ">=0.25.2,<0.26"
scikit-learn = ">=1.7.0,<2"
easydict = ">=1.13,<2"
umap-learn = ">=0.5.7,<0.6"
imageio = ">=2.37.0,<3"
motionmapperpy = {path = "./", editable=true}
